
```{r setup roadmap, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  warning = FALSE,
  message = FALSE
  )
```

# Roadmap

```{r roadmap}
library(tibble)
library(knitr)
tribble(
  ~name                   , ~implemented, ~paramchecks, ~unittested, ~documented, ~showcased,
  # scripting
  '`use_r.function`'      ,        TRUE,         TRUE,       FALSE,        TRUE,      FALSE,
  '`reformat_packaging`'  ,        TRUE,         TRUE,       FALSE,        TRUE,      FALSE,
  '`reformat_developing`' ,        TRUE,         TRUE,       FALSE,        TRUE,      FALSE,
  
  # documentation
  '`use_rmd.gitbook`'     ,        TRUE,         TRUE,       FALSE,        TRUE,      FALSE,
  
  
  # todo
  '`update_roadmap`'      ,       FALSE,        FALSE,       FALSE,       FALSE,      FALSE,
  '`add_reference`'       ,       FALSE,        FALSE,       FALSE,       FALSE,      FALSE,
  '`insert_table`'        ,       FALSE,        FALSE,       FALSE,       FALSE,      FALSE,
  '`insert_tribble`'      ,       FALSE,        FALSE,       FALSE,       FALSE,      FALSE,
  '`insert_codeblock`'    ,       FALSE,        FALSE,       FALSE,       FALSE,      FALSE,
) %>% knitr::kable()
```
