
#BEGIN: description
#' Reformat file generated by use_r.function to developing structure
#'
#'
#'
#' @usage
#' format_debugging(
#'   file_path,
#'   dry_run = TRUE
#' )
#'
#' @param file_path   \[character\], length 1, file path to reformat
#' @param dry_run   \[logical\], length 1, if TRUE, print the reformatted file
#'
#' @return
#'
#' @export
#' @importFrom magrittr %>%
#END: description
#BEGIN: code

format_debugging = function(
  file_path,
  dry_run = TRUE
  ) {

  #BEGIN: param checks
  if (!(length(file_path) == 1))
    rlang::abort(message = 'param file_path must satisfy length(v) == 1')

  if (!(class(file_path) == 'character'))
    rlang::abort(message = "param file_path must satisfy class(v) == 'character'")

  if (!(length(dry_run) == 1))
    rlang::abort(message = 'param dry_run must satisfy length(v) == 1')

  if (!(class(dry_run) == 'logical'))
    rlang::abort(message = "param dry_run must satisfy class(v) == 'logical'")
  #END: param checks

  #BEGIN: computation
  file_path %>% readr::read_lines() -> lines

  i_begin_description = which(lines == "#BEGIN: description")
  i_end_description = which(lines == "#END: description")
  i_begin_examples = which(lines == "#BEGIN: examples")
  i_end_examples = which(lines == "#END: examples")
  i_begin_code = which(lines == "#BEGIN: code")
  i_end_code = which(lines == "#END: code")

  if (!all(c(length(i_begin_description),length(i_end_description)) == 1))
    rlang::abort(message = "'#BEGIN: description' and '#END: description' must occur exactly 1 time in file")

  if (!all(c(length(i_begin_examples),length(i_end_examples)) == 1))
    rlang::abort(message = "'#BEGIN: examples' and '#END: examples' must occur exactly 1 time in file")

  if (!all(c(length(i_begin_code),length(i_end_code)) == 1))
    rlang::abort(message = "'#BEGIN: code' and '#END: code' must occur exactly 1 time in file")

  lines[
    c(
      # description goes first
      (i_begin_description):(i_end_description),
      # then code
      (i_begin_code):(i_end_code),
      # then examples
      (i_begin_examples):(i_end_examples)
    )
  ] -> reformated_lines

  if (dry_run) {
    reformated_lines %>% stringi::stri_join(collapse = '\n') %>% cat()
  } else {
    reformated_lines %>% readr::write_lines(file = file_path)
  }
  #END: computation

  #BEGIN: return
  #END: return
}

#END: code
#BEGIN: examples
#' @examples
#' #BEGIN: example
#' # observe that reformat_packaging moves examples next to description
#' # observe that reformat_developing moves examples next to description
#' use_r.function('myfun.R')
#' reformat_packaging('myfun.R',dry_run=FALSE)
#' reformat_developing('myfun.R',dry_run=TRUE)
#' #END: example
#END: examples
